language: generic

jobs:
  include:
    - stage: master
      if: branch = master
      env: FOO=branch_is_master
    - stage: development
      if: branch = development
      env: FOO=branch_is_development
      
script: echo $FOO
