language: generic

jobs:
  include:
    - stage: master
      if: branch IN (master)
      env: FOO=branch_is_master
    - stage: development
      if: branch IN (development)
      env: FOO=branch_is_development
      
script: echo $FOO
